// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReDataViz;

namespace ReDataViz.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20181106140953_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReDataViz.Models.DtvizMessage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Owner");

                    b.Property<string>("OwnerEmailID");

                    b.Property<string>("Text");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.ToTable("DtvizMessages");
                });

            modelBuilder.Entity("ReDataViz.Models.User", b =>
                {
                    b.Property<string>("EmailID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Passsword");

                    b.HasKey("EmailID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
